def war(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_WAR</Asset>
		<zIconName>IMPROVEMENT_SHRINE_WAR</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_TRAINING</zIndex>
				<iValue>20</iValue>
			</Pair>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def fire(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_FIRE</Asset>
		<zIconName>IMPROVEMENT_SHRINE_FIRE</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<EffectCity>EFFECTCITY_IMPROVEMENT_SHRINE_FIRE</EffectCity>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def sun(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_SUN</Asset>
		<zIconName>IMPROVEMENT_SHRINE_SUN</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
			<Pair>
				<zIndex>YIELD_ORDERS</zIndex>
				<iValue>5</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def water(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_WATER</Asset>
		<zIconName>IMPROVEMENT_SHRINE_WATER</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
			<Pair>
				<zIndex>YIELD_MONEY</zIndex>
				<iValue>100</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def love(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_LOVE</Asset>
		<zIconName>IMPROVEMENT_SHRINE_LOVE</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_GROWTH</zIndex>
				<iValue>10</iValue>
			</Pair>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def underworld(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_UNDERWORLD</Asset>
		<zIconName>IMPROVEMENT_SHRINE_UNDERWORLD</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<EffectCity>EFFECTCITY_IMPROVEMENT_SHRINE_UNDERWORLD</EffectCity>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def healing(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_HEALING</Asset>
		<zIconName>IMPROVEMENT_SHRINE_HEALING</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<EffectCity>EFFECTCITY_IMPROVEMENT_SHRINE_HEALING</EffectCity>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def kingship(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_KINGSHIP</Asset>
		<zIconName>IMPROVEMENT_SHRINE_KINGSHIP</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_CIVICS</zIndex>
				<iValue>20</iValue>
			</Pair>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def hearth(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_HEARTH</Asset>
		<zIconName>IMPROVEMENT_SHRINE_HEARTH</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>50</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")

def hunting(deity, nation):
    return(f"""
	<Entry>
		<zType>IMPROVEMENT_SHRINE_{deity}</zType>
		<Name>TEXT_IMPROVEMENT_SHRINE_{deity}</Name>
		<Class>IMPROVEMENTCLASS_SHRINE</Class>
		<Asset>ASSET_IMPROVEMENT_SHRINE_HUNTING</Asset>
		<zIconName>IMPROVEMENT_SHRINE_HUNTING</zIconName>
		<iBuildTurns>5</iBuildTurns>
		<iBuildCost>1</iBuildCost>
		<iPillageTurns>10</iPillageTurns>
		<iMaxCityCount>1</iMaxCityCount>
		<iMaxPlayerCount>1</iMaxPlayerCount>
		<bBuild>1</bBuild>
		<bTerritoryOnly>1</bTerritoryOnly>
		<bUrban>1</bUrban>
		<bRequiresUrban>1</bRequiresUrban>
		<bNoVegetation>1</bNoVegetation>
		<NationPrereq>NATION_{nation}</NationPrereq>
		<EffectCity>EFFECTCITY_IMPROVEMENT_SHRINE_HUNTING</EffectCity>
		<aiYieldCost>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>40</iValue>
			</Pair>
		</aiYieldCost>
		<aiYieldOutput>
			<Pair>
				<zIndex>YIELD_CULTURE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldOutput>
		<aiYieldPillage>
			<Pair>
				<zIndex>YIELD_STONE</zIndex>
				<iValue>20</iValue>
			</Pair>
		</aiYieldPillage>
		<abTerrainValid>
			<Pair>
				<zIndex>TERRAIN_URBAN</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_LUSH</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_TEMPERATE</zIndex>
				<bValue>1</bValue>
			</Pair>
			<Pair>
				<zIndex>TERRAIN_ARID</zIndex>
				<bValue>1</bValue>
			</Pair>
		</abTerrainValid>
	</Entry>""")